[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/"
  function = "personalize"

[[edge_functions]]
  path = "/corgis/*"
  function = "display-product"

[[edge_functions]]
  path = "/food/*"
  function = "display-product"

[[edge_functions]]
  path = "/*"
  function = "update-score"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/builders/products"
  status = 200

[[redirects]]
  from = "/corgis/*"
  to = "/product.html"
  status = 200

[[redirects]]
  from = "/food/*"
  to = "/product.html"
  status = 200
